# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "roda"
gem "gosduma", path: "../../model"

gem "redis"
gem "redis-rack-cache"

group :development, :test do
  gem "devup"
  gem "rack-test"
  gem "rspec"
  gem "shotgun"
  gem "warning"
end
