env:
  matrix:
  - APP_ENV=test BUNDLER_VERSION=2.1.4
language: ruby
cache: bundler
rvm:
- 2.6.6
services:
- docker
before_install:
- gem install bundler -v $BUNDLER_VERSION
bundler_args: "--jobs=3 --retry=3"
stages:
- test
- build
jobs:
  include:
  - stage: test
    name: RSpec
    before_script:
    - echo $MY_SECRET_ENV
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    - bundle exec devup up
    script:
    - bundle exec rspec
    after_success:
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
  - stage: test
    name: Lint
    script:
    - bundle exec standardrb
  - stage: test
    name: Docker Image
    before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    script:
    - docker build .
