env:
  - APP_ENV=test BUNDLER_VERSION=2.1.4 DOCKER_COMPOSE_VERSION=1.27.4

language: ruby
cache: bundler
rvm:
- 2.6.6
services:
- docker
before_install:
- gem install bundler -v $BUNDLER_VERSION
bundler_args: "--jobs=3 --retry=3"

jobs:
  include:
    - stage: test
      name: RSpec
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - "./cc-test-reporter before-build"
        - bundle exec devup up

      script:
        - bundle exec rspec

      after_script:
        - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

    - stage: test
      name: Lint
      script:
        - bundle exec standardrb
