# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "gosduma", path: "../../model"

gem "redis"
gem "redis-rack-cache"
gem "rufus-scheduler"

group :development do
  gem "devup"
  gem "rspec"
end
